<a href="https://colab.research.google.com/github/ryanxyed/HACKATHON/blob/main/python/ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**step1 :** installing dependencies

In [ ]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.5.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (7.5 kB)
Downloading mysql_connector_python-9.5.0-cp312-cp312-manylinux_2_28_x86_64.whl (34.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.1/34.1 MB 54.8 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.5.0

In [ ]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [ ]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 2.0 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

**step 2 :** connecting the oltp database

In [ ]:
import mysql.connector
import pandas as pd

conn = mysql.connector.connect(host="35.222.34.151",database="OLTP",user="team6",port="3306",password="t6ssss_DP")
cur=conn.cursor()

#**EXTRACT**

**step3 :** extracting the desired columns into a dataframe

In [ ]:
cur.execute('select customer_id,first_name,last_name,phone,phone_norm,city,state from customers')
customers_df=pd.DataFrame(cur.fetchall())
print(customers_df)

             0           1           2                    3          4  \
0            0  first_name   last_name                phone       city
1            1  Snemrpapzh       Obrbc  (281) +918746317213    Kolkata
2            2       Skrxg       Nznal        91-7051802512     Mumbai
3            3       Kuqaf    Mqagqaxw           6440213415     Jaipur
4            4  Fslqfheaey    Indjhwcp        +918342331444      Delhi
...        ...         ...         ...                  ...        ...
99996    99996   Egpnrplhq  Xvmbggylep        +919825107313      Delhi
99997    99997   Chjijdmdz  Yjgpjgsber        91-7003639123     Mumbai
99998    99998      Aphafq      Zbuetl          07855862591  Hyderabad
99999    99999    Ftcubqmn   Bsawjljvv        +916737793060     Mumbai
100000  100000  Anteotxxsq     Dlyfqou          65261-58934  Hyderabad

                    5            6
0               state  signup_date
1           Rajasthan   2024-05-01
2          Tamil Nadu   2023-03-05
3         West Bengal   2025-02-19
4          Tamil Nadu   2024-01-13
...               ...          ...
99996       Rajasthan   2024-06-21
99997     West Bengal   2024-10-05
99998   Uttar Pradesh   2025-05-11
99999     West Bengal   2023-03-21
100000     Tamil Nadu   2024-08-27

[100001 rows x 7 columns]

# **TRANSFORM**

**step 4 :** processing the data according to the requirements

transforming customers_df

In [ ]:

#renaming the columns with new column names

customers_df.columns = ['customer_id', 'first_name', 'last_name','phone','city','state','signup_date']
customers_df

,customer_id,first_name,last_name,phone,city,state,signup_date
0,0,first_name,last_name,phone,city,state,signup_date
1,1,Snemrpapzh,Obrbc,(281) +918746317213,Kolkata,Rajasthan,2024-05-01
2,2,Skrxg,Nznal,91-7051802512,Mumbai,Tamil Nadu,2023-03-05
3,3,Kuqaf,Mqagqaxw,6440213415,Jaipur,West Bengal,2025-02-19
4,4,Fslqfheaey,Indjhwcp,+918342331444,Delhi,Tamil Nadu,2024-01-13
...,...,...,...,...,...,...,...
99996,99996,Egpnrplhq,Xvmbggylep,+919825107313,Delhi,Rajasthan,2024-06-21
99997,99997,Chjijdmdz,Yjgpjgsber,91-7003639123,Mumbai,West Bengal,2024-10-05
99998,99998,Aphafq,Zbuetl,07855862591,Hyderabad,Uttar Pradesh,2025-05-11
99999,99999,Ftcubqmn,Bsawjljvv,+916737793060,Mumbai,West Bengal,2023-03-21
100000,100000,Anteotxxsq,Dlyfqou,65261-58934,Hyderabad,Tamil Nadu,2024-08-27

In [ ]:

# removing the first row because it is dummy

customers_df.drop(0,axis=0,inplace=True)
customers_df

,customer_id,first_name,last_name,phone,city,state,signup_date
1,1,Snemrpapzh,Obrbc,(281) +918746317213,Kolkata,Rajasthan,2024-05-01
2,2,Skrxg,Nznal,91-7051802512,Mumbai,Tamil Nadu,2023-03-05
3,3,Kuqaf,Mqagqaxw,6440213415,Jaipur,West Bengal,2025-02-19
4,4,Fslqfheaey,Indjhwcp,+918342331444,Delhi,Tamil Nadu,2024-01-13
5,5,Eispm,Jibzobi,+916136505587,Kolkata,Telangana,2025-05-12
...,...,...,...,...,...,...,...
99996,99996,Egpnrplhq,Xvmbggylep,+919825107313,Delhi,Rajasthan,2024-06-21
99997,99997,Chjijdmdz,Yjgpjgsber,91-7003639123,Mumbai,West Bengal,2024-10-05
99998,99998,Aphafq,Zbuetl,07855862591,Hyderabad,Uttar Pradesh,2025-05-11
99999,99999,Ftcubqmn,Bsawjljvv,+916737793060,Mumbai,West Bengal,2023-03-21
100000,100000,Anteotxxsq,Dlyfqou,65261-58934,Hyderabad,Tamil Nadu,2024-08-27

In [ ]:

#concatenating the 'first_name'+'last_name' to from a new column 'customer_name'

customers_df['customer_name']=customers_df['first_name']+' '+customers_df['last_name']
customers_df

,customer_id,first_name,last_name,phone,city,state,signup_date,customer_name
1,1,Snemrpapzh,Obrbc,(281) +918746317213,Kolkata,Rajasthan,2024-05-01,Snemrpapzh Obrbc
2,2,Skrxg,Nznal,91-7051802512,Mumbai,Tamil Nadu,2023-03-05,Skrxg Nznal
3,3,Kuqaf,Mqagqaxw,6440213415,Jaipur,West Bengal,2025-02-19,Kuqaf Mqagqaxw
4,4,Fslqfheaey,Indjhwcp,+918342331444,Delhi,Tamil Nadu,2024-01-13,Fslqfheaey Indjhwcp
5,5,Eispm,Jibzobi,+916136505587,Kolkata,Telangana,2025-05-12,Eispm Jibzobi
...,...,...,...,...,...,...,...,...
99996,99996,Egpnrplhq,Xvmbggylep,+919825107313,Delhi,Rajasthan,2024-06-21,Egpnrplhq Xvmbggylep
99997,99997,Chjijdmdz,Yjgpjgsber,91-7003639123,Mumbai,West Bengal,2024-10-05,Chjijdmdz Yjgpjgsber
99998,99998,Aphafq,Zbuetl,07855862591,Hyderabad,Uttar Pradesh,2025-05-11,Aphafq Zbuetl
99999,99999,Ftcubqmn,Bsawjljvv,+916737793060,Mumbai,West Bengal,2023-03-21,Ftcubqmn Bsawjljvv
100000,100000,Anteotxxsq,Dlyfqou,65261-58934,Hyderabad,Tamil Nadu,2024-08-27,Anteotxxsq Dlyfqou

In [ ]:

# removing the 'first_name' and 'last_name' because of 'customer_name'

customers_df.drop(['first_name','last_name'],axis=1,inplace=True)
customers_df

,customer_id,phone,city,state,signup_date,customer_name
1,1,(281) +918746317213,Kolkata,Rajasthan,2024-05-01,Snemrpapzh Obrbc
2,2,91-7051802512,Mumbai,Tamil Nadu,2023-03-05,Skrxg Nznal
3,3,6440213415,Jaipur,West Bengal,2025-02-19,Kuqaf Mqagqaxw
4,4,+918342331444,Delhi,Tamil Nadu,2024-01-13,Fslqfheaey Indjhwcp
5,5,+916136505587,Kolkata,Telangana,2025-05-12,Eispm Jibzobi
...,...,...,...,...,...,...
99996,99996,+919825107313,Delhi,Rajasthan,2024-06-21,Egpnrplhq Xvmbggylep
99997,99997,91-7003639123,Mumbai,West Bengal,2024-10-05,Chjijdmdz Yjgpjgsber
99998,99998,07855862591,Hyderabad,Uttar Pradesh,2025-05-11,Aphafq Zbuetl
99999,99999,+916737793060,Mumbai,West Bengal,2023-03-21,Ftcubqmn Bsawjljvv
100000,100000,65261-58934,Hyderabad,Tamil Nadu,2024-08-27,Anteotxxsq Dlyfqou

In [ ]:

#function to clean the 'phone' column

def clean_number(number):
  new=''
  for ch in number:
    if ch.isdigit():
      new+=ch
  return new[-10:] # return last 10 digits

In [ ]:

# replace old 'phone' column with new cleaned 'phone' column

customers_df['phone']=customers_df['phone'].apply(clean_number)
customers_df

,customer_id,phone,city,state,signup_date,customer_name
1,1,8746317213,Kolkata,Rajasthan,2024-05-01,Snemrpapzh Obrbc
2,2,7051802512,Mumbai,Tamil Nadu,2023-03-05,Skrxg Nznal
3,3,6440213415,Jaipur,West Bengal,2025-02-19,Kuqaf Mqagqaxw
4,4,8342331444,Delhi,Tamil Nadu,2024-01-13,Fslqfheaey Indjhwcp
5,5,6136505587,Kolkata,Telangana,2025-05-12,Eispm Jibzobi
...,...,...,...,...,...,...
99996,99996,9825107313,Delhi,Rajasthan,2024-06-21,Egpnrplhq Xvmbggylep
99997,99997,7003639123,Mumbai,West Bengal,2024-10-05,Chjijdmdz Yjgpjgsber
99998,99998,7855862591,Hyderabad,Uttar Pradesh,2025-05-11,Aphafq Zbuetl
99999,99999,6737793060,Mumbai,West Bengal,2023-03-21,Ftcubqmn Bsawjljvv
100000,100000,6526158934,Hyderabad,Tamil Nadu,2024-08-27,Anteotxxsq Dlyfqou

In [ ]:

# reordering the columns in a desired order

customers_df=customers_df[['customer_id','customer_name','phone','city','state','signup_date']]
customers_df

,customer_id,customer_name,phone,city,state,signup_date
1,1,Snemrpapzh Obrbc,8746317213,Kolkata,Rajasthan,2024-05-01
2,2,Skrxg Nznal,7051802512,Mumbai,Tamil Nadu,2023-03-05
3,3,Kuqaf Mqagqaxw,6440213415,Jaipur,West Bengal,2025-02-19
4,4,Fslqfheaey Indjhwcp,8342331444,Delhi,Tamil Nadu,2024-01-13
5,5,Eispm Jibzobi,6136505587,Kolkata,Telangana,2025-05-12
...,...,...,...,...,...,...
99996,99996,Egpnrplhq Xvmbggylep,9825107313,Delhi,Rajasthan,2024-06-21
99997,99997,Chjijdmdz Yjgpjgsber,7003639123,Mumbai,West Bengal,2024-10-05
99998,99998,Aphafq Zbuetl,7855862591,Hyderabad,Uttar Pradesh,2025-05-11
99999,99999,Ftcubqmn Bsawjljvv,6737793060,Mumbai,West Bengal,2023-03-21
100000,100000,Anteotxxsq Dlyfqou,6526158934,Hyderabad,Tamil Nadu,2024-08-27

transforming products_df

In [ ]:
cur.execute('select product_id,product_name,product_category_raw,product_category from products')
products_df=pd.DataFrame(cur.fetchall())
products_df.columns=['product_id','product_name','product_category_raw','list_price']
products_df.drop(0,axis=0,inplace=True)
def clean_category(raw):
  raw=raw.lower()
  if 'elec' in raw:
    raw= 'electronics'
  if '0' in raw:
    raw=raw.replace('0','o')
  if ' ' in raw:
    raw=raw.replace(' ','')
  if raw=='book':
    raw='books'
  if raw=='beauty&care':
    raw='beauty'
  if 'app' in raw:
    raw='apparel'
  raw=raw.title()
  return raw
products_df['product_category']=products_df['product_category_raw'].apply(clean_category)
products_df['product_category_raw']=products_df['product_category']
products_df.drop('product_category',axis=1,inplace=True)
products_df = products_df.rename(columns={'product_category_raw': 'product_category','list_price':'price'})


print(products_df)

      product_id      product_name product_category     price
1              1     Product-1-XQR            Books   3137.72
2              2     Product-2-IXV      Electronics    4865.7
3              3     Product-3-GMG      Electronics   15511.4
4              4     Product-4-UUF           Sports   9703.02
5              5     Product-5-CWR           Sports    2759.1
...          ...               ...              ...       ...
4996        4996  Product-4996-IVD            Books   7397.61
4997        4997  Product-4997-RFP            Books   11616.2
4998        4998  Product-4998-YDQ             Home  11710.36
4999        4999  Product-4999-EDL             Toys   9819.93
5000        5000  Product-5000-YNI           Beauty   17178.3

[5000 rows x 4 columns]

transforming payments_df

In [ ]:
cur.execute('select payment_id,order_id,payment_method,amount,payment_date from payments')
payments_df=pd.DataFrame(cur.fetchall())
payments_df.columns=['payment_id','order_id','payment_method','amount','payment_date']
payments_df.drop(0,axis=0,inplace=True)
print(payments_df)

        payment_id  order_id payment_method    amount payment_date
1                1         1     DEBIT_CARD    938.99   2024-01-07
2                2         2            UPI  25244.21   2023-01-26
3                3         3     DEBIT_CARD  56443.14   2023-12-18
4                4         4            COD  13060.57   2025-06-22
5                5         5     DEBIT_CARD  11633.50   2023-05-12
...            ...       ...            ...       ...          ...
199996      199996    199996     DEBIT_CARD  18943.62   2024-02-10
199997      199997    199997            COD   4501.26   2023-01-23
199998      199998    199998    CREDIT_CARD  23269.29   2023-07-09
199999      199999    199999     DEBIT_CARD  36722.98   2023-09-23
200000      200000    200000            COD   7747.21   2024-09-29

[200000 rows x 5 columns]

transforming date_df

In [ ]:
cur.execute('select order_id,DAYNAME(order_date),WEEK(order_date),MONTHNAME(order_date),QUARTER(order_date) from orders')
date_df=pd.DataFrame(cur.fetchall())
date_df.columns=['order_id','days','weeks','months','quarters']
date_df.drop(0,axis=0,inplace=True)
print(date_df)

        order_id    days  weeks     months  quarters
1             46  Sunday    1.0    January         1
2            291  Sunday    1.0    January         1
3            804  Sunday    1.0    January         1
4           1069  Sunday    1.0    January         1
5           1543  Sunday    1.0    January         1
...          ...     ...    ...        ...       ...
199996    197104  Monday   39.0  September         3
199997    197153  Monday   39.0  September         3
199998    198151  Monday   39.0  September         3
199999    199534  Monday   39.0  September         3
200000    199947  Monday   39.0  September         3

[200000 rows x 5 columns]

transforming order_items_df

In [ ]:
cur.execute('select order_item_id,order_id,product_id,unit_price,quantity,line_total from order_items')
order_items_df=pd.DataFrame(cur.fetchall())
order_items_df.columns=['order_item_id','order_id','product_id','unit_price','quantity','line_total']
order_items_df.drop(0,axis=0,inplace=True)
print(order_items_df)

        order_item_id  order_id  product_id unit_price  quantity line_total
1                   1         1        2155     938.99         1     938.99
2                   2         2        3943   12798.36         1   12798.36
3                   3         2        1815   12445.85         1   12445.85
4                   4         3        2487   12413.22         1   12413.22
5                   5         3          65   16232.12         1   16232.12
...               ...       ...         ...        ...       ...        ...
316159         316159    199997        3652    4501.26         1    4501.26
316160         316160    199998        4296   11253.65         1   11253.65
316161         316161    199998        3278   12015.64         1   12015.64
316162         316162    199999        2343   18361.49         2   36722.98
316163         316163    200000        2611    7747.21         1    7747.21

[316163 rows x 6 columns]

transforming returns_df

In [ ]:
cur.execute('select return_id,order_id,returned_date,refund_amount from returns')
returns_df=pd.DataFrame(cur.fetchall())
returns_df.columns=['return_id','order_id','return_date','refund_amount']
returns_df.drop(0,axis=0,inplace=True)
print(returns_df)

       return_id  order_id return_date refund_amount
1              1        27  2024-12-08      19131.45
2              2     23815  2023-02-08       1295.45
3              3     40121  2025-02-09      17197.50
4              4     25887  2024-06-29       6002.81
5              5     38060  2025-01-21      11506.57
...          ...       ...         ...           ...
12643      12643    178906  2025-03-01      15023.25
12644      12644    186893  2023-11-17      15911.91
12645      12645    183142  2025-07-22       3838.26
12646      12646    191087  2024-12-17       5794.79
12647      12647    174228  2024-03-10       8279.24

[12647 rows x 4 columns]

intialising fact_sales_df

In [ ]:
cur.execute('select order_id,customer_id,order_date,status,channel from orders')
fact_sales_df=pd.DataFrame(cur.fetchall())
fact_sales_df.columns=['order_id','customer_id','order_date','status','order_value']
fact_sales_df.drop(0,axis=0,inplace=True)
print(fact_sales_df)

        order_id  customer_id  order_date     status order_value
1              1        55426  2024-01-07  COMPLETED      938.99
2              2        29912  2023-01-26  COMPLETED    25244.21
3              3        74425  2023-12-18  COMPLETED    56443.14
4              4        46200  2025-06-22  COMPLETED    13060.57
5              5         2018  2023-05-12  COMPLETED     11633.5
...          ...          ...         ...        ...         ...
199996    199996        85299  2024-02-10  COMPLETED    18943.62
199997    199997        63602  2023-01-23  COMPLETED     4501.26
199998    199998        79250  2023-07-09  COMPLETED    23269.29
199999    199999        63883  2023-09-23  COMPLETED    36722.98
200000    200000        72579  2024-09-29   RETURNED     7747.21

[200000 rows x 5 columns]

# **LOAD**

loading all transformed tables into dimension tables

In [ ]:
import pandas as pd
from sqlalchemy import create_engine


# Example connection string:
# PostgreSQL:  'postgresql://user:password@localhost:5432/mydatabase'
# MySQL:        'mysql+pymysql://user:password@localhost:3306/mydatabase'

engine = create_engine('mysql+pymysql://team6:t6ssss_DP@35.222.34.151:3306/Team6')

# Write DataFrame to table 'employees'
customers_df.to_sql('dim_customers', engine, if_exists='append', index=False)

100000

In [ ]:
products_df.to_sql('dim_products', engine, if_exists='append', index=False)

5000

In [ ]:
payments_df.to_sql('dim_payments', engine, if_exists='append', index=False)

200000

In [ ]:
date_df.to_sql('dim_date',engine,if_exists='append',index=False)

200000

In [ ]:
order_items_df.to_sql('dim_order_items',engine, if_exists='append', index=False)

316163

In [ ]:
returns_df.to_sql('dim_returns',engine,if_exists='append',index=False)

12647

In [ ]:
fact_sales_df=pd.merge(fact_sales_df,order_items_df,on='order_id',how='left')
fact_sales_df.drop(columns=['unit_price','quantity','line_total'],axis=1,inplace=True)
fact_sales_df=pd.merge(fact_sales_df,payments_df,on='order_id',how='left')
fact_sales_df=pd.merge(fact_sales_df,returns_df,on='order_id',how='left')
fact_sales_df.drop(columns=['payment_method','amount','payment_date','return_date','refund_amount',],axis=1,inplace=True)
fact_sales_df

,order_id,customer_id,order_date,status,order_value,order_item_id,product_id,payment_id,payment_method,amount,payment_date,return_id,return_date,refund_amount
0,1,55426,2024-01-07,COMPLETED,938.99,1,2155,1,DEBIT_CARD,938.99,2024-01-07,NaN,NaN,NaN
1,2,29912,2023-01-26,COMPLETED,25244.21,2,3943,2,UPI,25244.21,2023-01-26,NaN,NaN,NaN
2,2,29912,2023-01-26,COMPLETED,25244.21,3,1815,2,UPI,25244.21,2023-01-26,NaN,NaN,NaN
3,3,74425,2023-12-18,COMPLETED,56443.14,4,2487,3,DEBIT_CARD,56443.14,2023-12-18,1426.0,2024-01-15,11683.32
4,3,74425,2023-12-18,COMPLETED,56443.14,5,65,3,DEBIT_CARD,56443.14,2023-12-18,1426.0,2024-01-15,11683.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316905,199997,63602,2023-01-23,COMPLETED,4501.26,316159,3652,199997,COD,4501.26,2023-01-23,NaN,NaN,NaN
316906,199998,79250,2023-07-09,COMPLETED,23269.29,316160,4296,199998,CREDIT_CARD,23269.29,2023-07-09,NaN,NaN,NaN
316907,199998,79250,2023-07-09,COMPLETED,23269.29,316161,3278,199998,CREDIT_CARD,23269.29,2023-07-09,NaN,NaN,NaN
316908,199999,63883,2023-09-23,COMPLETED,36722.98,316162,2343,199999,DEBIT_CARD,36722.98,2023-09-23,NaN,NaN,NaN
316909,200000,72579,2024-09-29,RETURNED,7747.21,316163,2611,200000,COD,7747.21,2024-09-29,NaN,NaN,NaN

In [ ]:
fact_sales_df.drop(columns=['payment_method','amount','payment_date','return_date','refund_amount',],axis=1,inplace=True)
fact_sales_df

,order_id,customer_id,order_date,status,order_value,order_item_id,product_id,payment_id,return_id
0,1,55426,2024-01-07,COMPLETED,938.99,1,2155,1,NaN
1,2,29912,2023-01-26,COMPLETED,25244.21,2,3943,2,NaN
2,2,29912,2023-01-26,COMPLETED,25244.21,3,1815,2,NaN
3,3,74425,2023-12-18,COMPLETED,56443.14,4,2487,3,1426.0
4,3,74425,2023-12-18,COMPLETED,56443.14,5,65,3,1426.0
...,...,...,...,...,...,...,...,...,...
316905,199997,63602,2023-01-23,COMPLETED,4501.26,316159,3652,199997,NaN
316906,199998,79250,2023-07-09,COMPLETED,23269.29,316160,4296,199998,NaN
316907,199998,79250,2023-07-09,COMPLETED,23269.29,316161,3278,199998,NaN
316908,199999,63883,2023-09-23,COMPLETED,36722.98,316162,2343,199999,NaN
316909,200000,72579,2024-09-29,RETURNED,7747.21,316163,2611,200000,NaN

In [ ]:
df_unique_id_all=0
df_unique_id_all = fact_sales_df.drop_duplicates(subset=['order_id'], keep='first')

In [ ]:
df_unique_id_all.to_sql('fact_sales',engine,if_exists='append',index=False)

200000

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive